/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Reward, RewardInterface } from "../Reward";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "totalRewardCal",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Reward__factory {
  static readonly abi = _abi;
  static createInterface(): RewardInterface {
    return new utils.Interface(_abi) as RewardInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Reward {
    return new Contract(address, _abi, signerOrProvider) as Reward;
  }
}
