/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lottery } from "./Lottery";
export type { StakingRewards } from "./StakingRewards";
export type { StakingToValidator } from "./StakingToValidator";
export type { TokenStaking } from "./TokenStaking";
export type { Erc20 } from "./Erc20";
export type { Multicall } from "./Multicall";
export type { Reward } from "./Reward";
export * as factories from "./factories";
export { Lottery__factory } from "./factories/Lottery__factory";
export { StakingRewards__factory } from "./factories/StakingRewards__factory";
export { StakingToValidator__factory } from "./factories/StakingToValidator__factory";
export { TokenStaking__factory } from "./factories/TokenStaking__factory";
export { Erc20__factory } from "./factories/Erc20__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
export { Reward__factory } from "./factories/Reward__factory";
